[project]
name = "ThreeSidedCoin"
version = "0.2"
description = "A pybullet simulation to find optimal 3-sided coin geometry."
authors = [ { name = "timjolson", email = "3058949-timjolson@users.noreply.gitlab.com" } ]
dependencies = [
    "numpy",
    "pybullet",
    "tqdm",
    "matplotlib",
    "scipy"
]

urls = { "Homepage" = "https://gitlab.com/timjolson/threesidedcoin" }
readme = "README.md"
license = { file = "LICENSE" }

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"